overlay: 1.0.0
info:
  title: API Evangelist overlay for Trulioo Business Verification Authentication …………
  version: 1.0.0
extends: openapi/trulioo-configuration-api-openapi.yml
x-generated: '2026-10-08'
x-method: generated
x-source:
- apis.yml
- conventions/trulioo-conventions.yml
- authentication/trulioo-authentication.yml
- rate-limits/trulioo-rate-limits.yml
- errors/trulioo-error-codes.yml
actions:
- target: $.info
  update:
    x-apievangelist:
      provider: trulioo
      conventions: conventions/trulioo-conventions.yml
      authentication: authentication/trulioo-authentication.yml
      errors: errors/trulioo-error-codes.yml
      rate_limits: rate-limits/trulioo-rate-limits.yml
      sandbox: sandbox/trulioo-sandbox.yml
      lifecycle: lifecycle/trulioo-lifecycle.yml
- target: $
  update:
    externalDocs:
      description: Trulioo API reference
      url: https://developer.trulioo.com/reference/api-reference-overview
- target: $.info
  update:
    x-authentication-docs: https://developer.trulioo.com/reference/authentication
    x-error-docs: https://developer.trulioo.com/reference/errors
    x-regions-docs: https://developer.trulioo.com/reference/multi-region-hosting
